name: 'Tag and Release'
description: 'Create a Git tag and release using GitVersion and PyGithub'
author: 'Your Name'
inputs:
  github_token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  release_message:
    description: "Note-worthy description of changes in release"
    required: false
outputs:
  release_url:
    description: "URL to the Release HTML Page"
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true
        disableCache: true
        configFilePath: GitVersion.yml
      
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub colorlog

    - name: Create Git Tag and Release
      id: release_step
      run: |
        python main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ steps.gitversion.outputs.semVer }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        RELEASE_MESSAGE: "${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}"

    - name: Release URL
      shell: bash
      run: echo "The release URL is ${{ steps.release_step.outputs.release_url }}"
