name: 'Tag and Release'
description: 'Create a Git tag and release using GitVersion and PyGithub'
author: 'Your Name'
inputs:
  github_token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
outputs:
  tag_name:
    description: 'The name of the tag created'
    value: ""
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'
        useConfigFile: false

    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub


    - name: Create Git Tag and Release
      run: |
        python main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ steps.gitversion.outputs.SemVer }}
        GITHUB_REPOSITORY: ${{ github.repository }}
